Prepare metadata.txt for release
nsidc/qgreenland-plugin pull request #38
Opened 2021-12-17 07:12 UTC by ghtmtt

2021-12-20 17:17 UTC, trey-stafford requested changes
Actually, before we merge this and do a release, let's change the plugin name to `QGreenland Custom`.

2021-12-20 17:17 UTC, MattF-NSIDC requested changes

2021-12-20 17:17 UTC, MattF-NSIDC commented on metadata.txt
Hey @ghtmtt can you change the `name` field on line `6` to `QGreenland Custom`? We decided that we are going to brand the plugin as `QGreenland Custom` and the zip package as `QGreenland Core`.

2021-12-21 07:01 UTC, ghtmtt commented
> We decided that we are going to brand the plugin as QGreenland Custom and the zip package as QGreenland Core

what do you exactly mean by naming the zip package? We only need to create the zip package to upload the plugin to the QGIS server, the user won't ever see the zip package...

2021-12-21 14:55 UTC, trey-stafford commented
> > We decided that we are going to brand the plugin as QGreenland Custom and the zip package as QGreenland Core
> 
> what do you exactly mean by naming the zip package? We only need to create the zip package to upload the plugin to the QGIS server, the user won't ever see the zip package...

Hey @ghtmtt sorry we were not clear on this. The zip package we are referring to is the QGreenland zip package that comes pre-configured with a project file and data, which is already available on our website, https://qgreenland.org/download.

Nothing in this repo needs to be branded as 'QGreenland Core'. We just want the name of the plugin to be renamed to 'QGreenland Custom'.

2021-12-21 21:26 UTC, MattF-NSIDC approved these changes

2021-12-22 06:36 UTC, ghtmtt commented
@trey-stafford got it. So the changes made in the current `metadata.txt` file are enough for this release right?

2021-12-22 14:48 UTC, trey-stafford approved these changes

2021-12-22 14:49 UTC, trey-stafford commented
> @trey-stafford got it. So the changes made in the current `metadata.txt` file are enough for this release right?

Yes! Thanks, @ghtmtt!

2021-12-23 16:11 UTC, merged